### ISSUE TITLE
brew-max ?

### ISSUE THREAD

**Issue by AlJohri** [jjangsangy/Dotfiles#1]
Hi @jjangsangy! I just wanted to say I really love your entire Dotfiles repository and bash scripts in general. They're great to follow as I'm trying to write my own dotfiles https://github.com/AlJohri/dotfiles.

I was wondering what was the purpose of your brew-max script and in which situations have you found it useful?

I used to do something similar however I found my scripts taking much, much longer as homebrew no longer used pre-compiled binaries (bottles) for certain formulae. I pretty much removed all with-\* options except the ones I really need. Would love to hear your thoughts.

Thanks for your time!

**Comment by jjangsangy** [comment]
Hey @AlJohri, thanks the compliments.

The reason why I wrote `brew-max.sh` was because of certain packages like `ffmpeg`, `avconv`, and `imagemagick` which had a lot of different options, most which were pretty important as dependencies for kegs like `youtube-dl` and wanted a script to just install all the optional packages.

It has gotten better over time, and a lot of `homebrew` kegs have good defaults.

But I do find this script pretty useful for when I don't mind the additional compilation time in order to get the plugins I need.

Let me know if you have any questions. Although my `Dotfiles` were originally written for me to maintain my own packages, it would be great to get feedback for others so that I can generalize these scripts for other people as well.

Cheers
- Sang Han
